version: '3.8'
services:
  dev-db:
    image: 'postgres:15'
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    networks:
      - artvibe
  test-db:
    image: 'postgres:15'
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    networks:
      - artvibe
networks:
  artvibe:
